configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
      performance:
        maxDiskBandwitdh: 16777216
    storage:
      gcs:
        bucket: stackgres-e2e-backup-with-gce-storage
        gcpCredentials:
          secretKeySelectors:
            serviceAccountJSON:
              name: gke-service-account
              key: gke-service-account.json
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  prometheusAutobind: false
minio:
  create: false
