apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgbackups.stackgres.io
spec:
  group:  stackgres.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresBackup
    listKind: StackGresBackupList
    plural: sgbackups
    singular: sgbackup
  validation:
    openAPIV3Schema:
      type: object
      description: "Status of backup"
      properties:
        spec:
          type: object
          properties:
            cluster:
              type: string
              description: "The name of the cluster where the backup will or has been taken."
            isPermanent:
              type: boolean
              description: "Indicate if this backup is permanent and should not be removed by retention process."
        status:
          type: object
          properties:
            phase:
              type: string
              enum: [ "Pending", "Completed", "Failed" ]
              description: "The phase of the backup."
            pod:
              type: string
              description: "The name of pod assigned to this backup."
            failureReason:
              type: string
              description: "If the phase is failed this field will contain a message with the failure reason."
            backupConfig:
              type: object
              description: "The name of the backup configuration used to perform this backup."
              properties:
                compressionMethod:
                  type: string
                  description: "To configure compression method used for backups. Possible options are: lz4, lzma, brotli. Default method is lz4. LZ4 is the fastest method, but compression ratio is bad. LZMA is way much slower, however it compresses backups about 6 times better than LZ4. Brotli is a good trade-off between speed and compression ratio which is about 3 times better than LZ4."
                  enum: [ "lz4", "lzma", "brotli" ]
                storage:
                  type: object
                  description: "Backup storage configuration"
                  properties:
                    type:
                      type: string
                      enum: [ "s3", "gcs", "azureblob" ]
                      description: "Type of storage:\n- s3: Amazon Web Services S3\n- gcs: Google Clooud Storage\n- azureblob: Azure Blob Storage"
                    s3:
                      type: object
                      description: "Amazon Web Services S3 configuration"
                      properties:
                        prefix:
                          type: string
                          pattern: '(s3|https?)://[^/]+(/[^/]*)*$'
                          description: "The AWS S3 bucket and prefix (eg. s3://bucket/path/to/folder)."
                        credentials:
                          type: object
                          description: "The credentials to access AWS S3 for writing and reading."
                          properties:
                            accessKey:
                              type: object
                              description: "AWS Access Key ID secret"
                              properties:
                                key:
                                  type: string
                                  description: "The key of the secret to select from. Must be a valid secret key."
                                name:
                                  type: string
                                  description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                              required: [ "key", "name" ]
                            secretKey:
                              type: object
                              description: "AWS Secret Access Key"
                              properties:
                                key:
                                  type: string
                                  description: "The key of the secret to select from. Must be a valid secret key."
                                name:
                                  type: string
                                  description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                              required: [ "key", "name" ]
                          required: [ "accessKey", "secretKey" ]
                        region:
                          type: string
                          description: "The AWS S3 region. Region can be detected using s3:GetBucketLocation, but if you wish to avoid this API call or forbid it from the applicable IAM policy, specify this property."
                        endpoint:
                          type: string
                          description: "Overrides the default hostname to connect to an S3-compatible service. i.e, http://s3-like-service:9000."
                        forcePathStyle:
                          type: boolean
                          description: "To enable path-style addressing(i.e., http://s3.amazonaws.com/BUCKET/KEY) when connecting to an S3-compatible service that lack of support for sub-domain style bucket URLs (i.e., http://BUCKET.s3.amazonaws.com/KEY). Defaults to false."
                        storageClass:
                          type: string
                          description: "By default, the \"STANDARD\" storage class is used. Other supported values include \"STANDARD_IA\" for Infrequent Access and \"REDUCED_REDUNDANCY\" for Reduced Redundancy."
                      required: [ "prefix", "credentials" ]
                    gcs:
                      type: object
                      description: "Google Cloud Storage configuration"
                      properties:
                        prefix:
                          type: string
                          description: "Specify where to store backups (eg. gs://x4m-test-bucket/walg-folder)."
                          pattern: "^gs://[^/]+(/[^/]*)*$"
                        credentials:
                          type: object
                          description: "The credentials to access GCS for writing and reading."
                          properties:
                            serviceAccountJsonKey:
                              type: object
                              description: "A service account json key from GCP."
                              properties:
                                key:
                                  type: string
                                  description: "The key of the secret to select from. Must be a valid secret key."
                                name:
                                  type: string
                                  description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                              required: [ "key", "name" ]
                          required: [ "serviceAccountJsonKey" ]
                      required: [ "prefix", "credentials" ]
                    azureblob:
                      type: object
                      description: "Azure Blob Storage configuration"
                      properties:
                        prefix:
                          type: string
                          description: "Specify where to store backups in Azure storage (eg. azure://test-container/walg-folder)."
                          pattern: "^azure://[^/]+(/[^/]*)*$"
                        credentials:
                          type: object
                          description: "The credentials to access Azure Blob Storage for writing and reading."
                          properties:
                            account:
                              type: object
                              description: "The name of the storage account."
                              properties:
                                key:
                                  type: string
                                  description: "The key of the secret to select from. Must be a valid secret key."
                                name:
                                  type: string
                                  description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                              required: [ "key", "name" ]
                            accessKey:
                              type: object
                              description: "The primary or secondary access key for the storage account."
                              properties:
                                key:
                                  type: string
                                  description: "The key of the secret to select from. Must be a valid secret key."
                                name:
                                  type: string
                                  description: "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
                              required: [ "key", "name" ]
                          required: [ "account", "accessKey" ]
                      required: [ "prefix", "credentials" ]
                  required: ["type"]
              required: ["storage"]
            name:
              type: string
              description: "The name of the backup."
            time:
              type: string
              format: date-time
              description: "The date of the backup."
            walFileName:
              type: string
              description: "The WAL file name when backup was started."
            startTime:
              type: string
              format: date-time
              description: "The start time of backup."
            finishTime:
              type: string
              format: date-time
              description: "The finish time of backup."
            hostname:
              type: string
              description: "The hostname of instance where the backup is taken."
            dataDir:
              type: string
              description: "The data directory where the backup is taken."
            pgVersion:
              type: string
              description: "The PostgreSQL version of the server where backup is taken."
            startLsn:
              type: string
              description: "The LSN of when backup started."
            finishLsn:
              type: string
              description: "The LSN of when backup finished."
            isPermanent:
              type: boolean
              description: "Indicate internally if this backup is permanent and should not be removed by retention process."
            systemIdentifier:
              type: string
              description: "The internal system identifier of this backup."
            uncompressedSize:
              type: integer
              format: int64
              description: "The size in bytes of the uncompressed backup."
            compressedSize:
              type: integer
              format: int64
              description: "The size in bytes of the compressed backup."
            controlData:
              type: object
              description: "An object containing data from the output of pg_controldata on the backup."
            tested:
              type: boolean
              description: "true if the backup has been tested."
