apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgclusters.stackgres.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group:  stackgres.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresCluster
    listKind: StackGresClusterList
    plural: sgclusters
    singular: sgcluster
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      description: "Params for StackGres Cluster creation"
      properties:
          spec:
            type: object
            properties:
              instances:
                type: integer
                # minimum: 1 # see https://gitlab.com/ongresinc/stackgres/issues/102
                description: "Number of instances to be created"
              pgVersion:
                type: string
                description: "PostgreSQL version for the new cluster"
              pgConfig:
                type: string
                description: "PostgreSQL configuration to apply"
              connectionPoolingConfig:
                type: string
                description: "Pooling configuration to apply"
              resourceProfile:
                type: string
                description: "Resource profile size to apply"
              volumeSize:
                type: string
                pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi|Ti)$'
                description: "Storage volume size"
              storageClass:
                type: string
                description: "Storage class name to be used for the cluster"
              backupConfig:
                type: string
                description: "Backup config to apply"
              restore:
                type: object
                description: "Restore config to apply"
                properties:
                  fromBackup:
                    type: string
                    description: "UID of the Backup CR to restore"
                  downloadDiskConcurrency:
                    type: integer
                    description: "Indicate how many download streams to have during restoration"
              sidecars:
                type: array
                items:
                  type: string
                description: "List of sidecars to include in the cluster"
              prometheusAutobind:
                type: boolean
                description: "If enabled a ServiceMonitor will be created for each Prometheus instance found in order to collect metrics"
            required: [
              "instances",
              "pgVersion",
              "volumeSize"
            ]




