apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sginstanceprofiles.stackgres.io
spec:
  group:  stackgres.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: SGInstanceProfile
    listKind: SGInstanceProfileList
    plural: sginstanceprofiles
    singular: sginstanceprofile
    shortNames:
      - sginp
  validation:
    openAPIV3Schema:
      required: ["spec"]
      type: object
      description: "Params for resources"
      properties:
        spec:
          type: object
          properties:
            cpu:
              type: string
              pattern: '^[1-9][0-9]*[m]?$'
              description: "CPU amount to be used"
            memory:
              type: string
              pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi)$'
              description: "Memory size to be used"
          required: ["cpu","memory"]