apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgpgconfigs.stackgres.io
spec:
  group:  stackgres.io
  versions:
    - name: v1beta1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: SGPostgresConfig
    listKind: SGPostgresConfigList
    plural: sgpgconfigs
    singular: sgpgconfig
    shortNames:
      - sgpgc
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      description: "Params for PostgreSQL configuration"
      properties:
        spec:
          type: object
          properties:
            postgresVersion:
              type: string
              description: "PostgreSQL configuration version"
            postgresql.conf:
              type: object
              description: "List of PostgreSQL configuration parameters with their values"
          required: ["postgresVersion","postgresql.conf"]