config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
  backup:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
    fullWindow: 1
    diskRateLimit: 16777216
    minio:
      create: false
    s3:
      prefix: s3://stackgres-e2e
      accessKey:
          name: s3-credentials
          key: accessKeyId
      secretKey:
          name: s3-credentials
          key: secretAccessKey
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
