{{ if .Values.cluster.create }}
apiVersion: stackgres.io/v1beta1
kind: SGCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  instances: {{ .Values.cluster.instances }}
  postgresVersion: '{{ .Values.config.postgresql.version }}'
  pgConfig: '{{ .Values.cluster.pgconfig }}'
  connectionPoolingConfig: '{{ .Values.cluster.poolingconfig }}'
  resourceProfile: '{{ .Values.cluster.profile }}'
  {{- if .Values.cluster.backupconfig }}
  backupConfig: '{{ .Values.cluster.backupconfig }}'
  {{- end }}
  {{- if .Values.cluster.restore }}
  restore:
    fromBackup: {{ .Values.cluster.restore.fromBackup }}
    {{- if .Values.cluster.restore.downloadDiskConcurrency }}
    downloadDiskConcurrency: {{ .Values.cluster.restore.downloadDiskConcurrency }}
    {{- end }}    
  {{- end }}
  volumeSize: '{{ .Values.cluster.volumeSize }}'
  {{- if .Values.cluster.storageClass }}
  {{- if eq "-" .Values.cluster.storageClass }}
  storageClass: ""
  {{- else }}
  storageClass: {{ .Values.cluster.storageClass }}
  {{- end }}
  {{- end }}
  {{- if .Values.sidecar.prometheus.allowAutobind }}
  prometheusAutobind: {{ .Values.sidecar.prometheus.allowAutobind }}
  {{- else }}
  prometheusAutobind: false
  {{- end }}
  sidecars:
  {{- if .Values.sidecar.pooling }}
  - connection-pooling
  {{- end }}
  {{- if .Values.sidecar.util }}
  - postgres-util
  {{- end }}
  {{- if .Values.nonProduction }}
  nonProduction:
  {{- if .Values.nonProduction.disableClusterPodAntiAffinity }}
    disableClusterPodAntiAffinity: {{ .Values.nonProduction.disableClusterPodAntiAffinity }}
  {{- end }}
  {{- end }}
{{ end }}