{{ if .Values.cluster.create }}
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  instances: {{ .Values.cluster.instances }}
  pgVersion: '{{ .Values.config.postgresql.version }}'
  pgConfig: '{{ .Values.cluster.pgconfig }}'
  connectionPoolingConfig: '{{ .Values.cluster.poolingconfig }}'
  resourceProfile: '{{ .Values.cluster.profile }}'
  {{- if .Values.cluster.backup.create }}
  backupConfig: '{{ .Values.cluster.backup.name }}'
  {{- end }}
  volumeSize: '{{ .Values.cluster.volumeSize }}'
  {{- if .Values.cluster.storageClass }}
  {{- if eq "-" .Values.cluster.storageClass }}
  storageClass: ""
  {{- else }}
  storageClass: {{ .Values.cluster.storageClass }}
  {{- end }}
  {{- end }}
  {{- if .Values.sidecar.prometheus.create }}
  prometheusAutobind: {{ .Values.sidecar.prometheus.allowAutobind }}
  {{- else }}
  prometheusAutobind: false
  {{- end }}
  sidecars:
  {{- if .Values.sidecar.pooling }}
  - connection-pooling
  {{- end }}
  {{- if .Values.sidecar.util }}
  - postgres-util
  {{- end }}
  {{- if .Values.sidecar.prometheus.create }}
  - prometheus-postgres-exporter
  {{- end }}
{{ end }}