{{ if .Values.cluster.create }}
apiVersion: stackgres.io/v1beta1
kind: SGCluster
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  instances: {{ .Values.cluster.instances }}
  postgresVersion: '{{ .Values.config.postgresql.version }}'
  configurations: 
    sgPostgresConfig: '{{ .Values.cluster.pgconfig }}'
    sgPoolingConfig: '{{ .Values.cluster.poolingconfig }}'
    {{- if .Values.cluster.backupconfig }}
    sgBackupConfig: '{{ .Values.cluster.backupconfig }}'
    {{- end }}
  sgInstanceProfile: '{{ .Values.cluster.profile }}'
  {{- if .Values.cluster.restore }}
  initialData:
    restore:
      fromBackup: {{ .Values.cluster.restore.fromBackup }}
      {{- if .Values.cluster.restore.downloadDiskConcurrency }}
      downloadDiskConcurrency: {{ .Values.cluster.restore.downloadDiskConcurrency }}
    {{- end }}    
  {{- end }}
  pods:
    persistentVolume:
      size: '{{ .Values.cluster.volumeSize }}'
    {{- if .Values.sidecar.pooling }}
    disableConnectionPooling: false
    {{- else }}
    disableConnectionPooling: true
    {{- end }}  
    {{- if .Values.sidecar.util }}
    disablePostgresUtil: false
    {{- else }}
    disablePostgresUtil: true
    {{- end }}
    {{- if .Values.sidecar.prometheus.enabled }}
    disableMetricsExporter: false
    {{- else }}
    disableMetricsExporter: true
    {{- end }}
  {{- if .Values.cluster.storageClass }}
  {{- if eq "-" .Values.cluster.storageClass }}
  storageClass: ""
  {{- else }}
  storageClass: {{ .Values.cluster.storageClass }}
  {{- end }}
  {{- end }}
  {{- if .Values.cluster.distributedLogs.enabled }}
  distributedLogs:
    sgDistributedLogs: {{ .Values.cluster.distributedLogs.name }}
  {{- end }}
  {{- if .Values.sidecar.prometheus.allowAutobind }}
  prometheusAutobind: {{ .Values.sidecar.prometheus.allowAutobind }}
  {{- else }}
  prometheusAutobind: false
  {{- end }}
  {{- if .Values.nonProductionOptions }}
  nonProductionOptions:
  {{- if not .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
    disableClusterPodAntiAffinity: false
  {{- else }}
    disableClusterPodAntiAffinity: {{ .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
  {{- end }}
  {{- end }}
{{ end }}