{{ if and .Values.config.create .Values.cluster.backup.create (not (or .Values.cluster.backup.volume .Values.cluster.backup.s3 .Values.cluster.backup.gcs .Values.cluster.backup.azureblob)) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nfs
  labels:
    role: nfs
spec:
  type: ClusterIP
  ports:
    - port: 2049
      targetPort: nfs
      protocol: TCP
      name: nfs
    - port: 20048
      targetPort: mountd
      protocol: TCP
      name: mountd
    - port: 111
      targetPort: rpcbind
      protocol: TCP
      name: rpcbind
  selector:
    role: nfs
{{ end }}