{{ if and .Values.config.create .Values.cluster.backup.create (not (or .Values.cluster.backup.volume .Values.cluster.backup.s3 .Values.cluster.backup.gcs .Values.cluster.backup.azureblob)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-nfs
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
  - patch
- apiGroups: ["", storage.k8s.io"]
  resources:
  - storageclasses
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
{{ end }}