{{ if and .Values.config.create .Values.cluster.backup.create (not (or .Values.cluster.backup.volume .Values.cluster.backup.s3 .Values.cluster.backup.gcs .Values.cluster.backup.azureblob)) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nfs
  labels:
    role: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      serviceAccountName: "{{ .Release.Name }}-nfs"
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SERVICE_NAME
            value: "{{ .Release.Name }}-nfs.{{ .Release.Namespace }}.svc.cluster.local"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /exports
            name: backup
  volumeClaimTemplates:
    - metadata:
        name: backup
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.cluster.backup.storageClass }}
        {{- if eq "-" .Values.cluster.backup.storageClass }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.cluster.backup.storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.cluster.backup.volumeSize }}
{{ end }}