{{ if .Values.config.create }}
apiVersion: stackgres.io/v1alpha1
kind: StackGresConnectionPoolingConfig
metadata:
  name: {{ .Values.cluster.poolingconfig }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  {{- with (index .Values.config.pgbouncer "pgbouncer.ini") }}
  pgbouncer.ini:
  {{- range $key, $value := . }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  {{- end }}
{{ end }}
