{{ if .Values.config.create }}
apiVersion: stackgres.io/v1alpha1
kind: StackGresPostgresConfig
metadata:
  name: {{ .Values.cluster.pgconfig }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  pgVersion: "{{ index (.Values.config.postgresql.version | splitList ".") 0 }}"
  {{- with (index .Values.config.postgresql "postgresql.conf") }}
  postgresql.conf:
  {{- range $key, $value := . }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  {{- end }}
{{ end }}
