{{ if .Values.config.create }}
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresPostgresConfig
metadata:
  name: {{ .Values.cluster.pgconfig }}
  {{- if .Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  pgVersion: "{{ index (.Values.config.postgresql.version | splitList ".") 0 }}"
  postgresql.conf:
      shared_buffers: '256MB'
      random_page_cost: '1.5'
      password_encryption: 'scram-sha-256'
      wal_compression: 'on'
{{ end }}
