{{ if .Values.profiles }}
{{- range .Values.profiles }}
---
apiVersion: stackgres.io/v1beta1
kind: SGInstanceProfile
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "stackgres-cluster.name" $ }}
    chart: {{ template "stackgres-cluster.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  {{- if $.Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  cpu: "{{ .cpu }}"
  memory: "{{ .memory }}"
{{- end }}
{{- end }}