{{ if and .Values.distributedLogs.enabled .Values.distributedLogs.create }}
apiVersion: stackgres.io/v1
kind: SGDistributedLogs
metadata:
  name: {{ .Values.cluster.distributedLogs.sgDistributedLogs }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    helm.sh/hook: "pre-install"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  persistentVolume:
    size: {{ .Values.distributedLogs.persistentVolume.size }}
    {{- if .Values.distributedLogs.persistentVolume.storageClass }}
    {{- if eq "-" .Values.distributedLogs.persistentVolume.storageClass }}
    storageClass: ""
    {{- else }}
    storageClass: {{ .Values.distributedLogs.persistentVolume.storageClass }}
    {{- end }}
    {{- end }}
  {{- if .Values.nonProductionOptions }}
  nonProductionOptions:
  {{- if not .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
    disableClusterPodAntiAffinity: false
  {{- else }}
    disableClusterPodAntiAffinity: {{ .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
  {{- end }}
  {{- end }}
{{ end }}
