{{ if .Values.configurations.create }}
apiVersion: stackgres.io/v1beta1
kind: SGPostgresConfig
metadata:
  name: {{ .Values.cluster.configurations.sgPostgresConfig }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  postgresVersion: "{{ index (.Values.cluster.postgresVersion | splitList ".") 0 }}"
  {{- with (index .Values.configurations.postgresconfig "postgresql.conf") }}
  postgresql.conf:
  {{- range $key, $value := . }}
    {{ $key }}: '{{ $value }}'
  {{- end }}
  {{- end }}
{{ end }}
