{{ if .Values.configurations.create }}
apiVersion: stackgres.io/v1beta1
kind: SGPoolingConfig
metadata:
  name: {{ .Values.cluster.configurations.sgPoolingConfig }}
  labels:
    app: {{ template "stackgres-cluster.name" . }}
    chart: {{ template "stackgres-cluster.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.cluster.create }}
  annotations:
    "helm.sh/hook": "pre-install"
  {{- end }}
spec:
  pgBouncer:
    {{- with (index .Values.configurations.poolingconfig.pgBouncer "pgbouncer.ini") }}
    pgbouncer.ini:
    {{- range $key, $value := . }}
      {{ $key }}: '{{ $value }}'
    {{- end }}
    {{- end }}
{{ end }}
