
enforce release:
  image: docker.io/ongres/ubi-graalvm-maven:19.3.1-java8
  stage: check-release
  tags:
    - stackgres-runner
  dependencies:
    - build
  script:
    - MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -DskipTests -Dquarkus.skipAugmentation=true"
    - 'mvn $MAVEN_CLI_OPTS enforcer:enforce@enforce-no-snapshots'
  only:
    variables:
      - $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
