build ui:
  image: alpine:3.12
  stage: post-build
  script:
  - apk add py3-pip jq
  - pip install yamllint yq
  - sh -x stackgres-k8s/src/admin-ui/build.sh
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/src/admin-ui/target

build documentation:
  image: monachus/hugo
  stage: post-build
  dependencies:
    - build
  script:
  - apt update -y
  - apt install -y jq python-pip
  - pip install yq
  - sh -x stackgres-k8s/src/api-web/src/main/swagger/build.sh
  - sh -x doc/build.sh
  - STACKGRES_VERSION="$(echo 'import xml.etree.ElementTree as ET; print ET.parse("stackgres-k8s/src/pom.xml").getroot().find("{%s}version" % "http://maven.apache.org/POM/4.0.0").text' | python)"
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      DOCUMENTATION_BASE_URL="$PRODUCTION_DOCUMENTATION_BASE_URL"
    else
      DOCUMENTATION_BASE_URL="https://ongresinc.gitlab.io/stackgres/$STACKGRES_VERSION"
    fi
  - mkdir -p "doc/public/$STACKGRES_VERSION"
  - hugo -v --source doc --destination "$(pwd)/doc/public/$STACKGRES_VERSION" --baseURL="$DOCUMENTATION_BASE_URL"
  - cp -a "doc/public/$STACKGRES_VERSION" doc/public/latest
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - doc/public

build helm packages:
  image: dtzar/helm-kubectl:3.3.1
  stage: post-build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-packages.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target

build helm templates:
  image: dtzar/helm-kubectl:3.3.1
  stage: post-build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-templates.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target
