apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operatorName }}
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.operatorNamespace }}
  {{- end }}
rules:
- apiGroups: ["", "apps", "extensions", "rbac.authorization.k8s.io"] # "" indicates the core API group
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - configmaps
  - secrets
  - statefulsets
  - deployments
  - clusterroles
  - clusterrolebindings
  - serviceaccounts
  - namespaces
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups: ["apiextensions.k8s.io", "customresourcedefinitions.apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups: ["{{ .Values.group }}"]
  resources:
  - sgclusters
  verbs:
  - watch
  - list
  - get
  - update