apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operatorName }}
  namespace: {{ .Values.operatorNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operatorName }}
  namespace: {{ .Values.operatorNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.operatorName }}
  apiGroup: rbac.authorization.k8s.io