apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sgdbops.stackgres.io
spec:
  group: stackgres.io
  scope: Namespaced
  names:
    kind: SGDbOps
    listKind: SGDbOpsList
    plural: sgdbops
    singular: sgdbops
    shortNames:
      - sgdo
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          required: ["metadata", "spec"]
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  description: |
                    Name of the Database Operation. A database operation represents a ""kind"" of operation on a StackGres cluster, classified by a given name. The operation reference one SGCluster by its name. Following [Kubernetes naming conventions](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md), it must be an rfc1035/rfc1123 subdomain, that is, up to 253 characters consisting of one or more lowercase labels separated by `.`. Where each label is an alphanumeric (a-z, and 0-9) string, with a maximum length of 63 characters, with the `-` character allowed anywhere except the first or last character.

                    The name must be unique across all database operations in the same namespace."
            spec:
              type: object
              properties:
                sgCluster:
                  type: string
                  description: |
                    The name of SGCluster on which the operation will be performed
                op:
                  type: string
                  description: |
                    The kind of operation that will be performed on the SGCluster. Available operations are:

                    * `benchmark`: run a benchmark on the specified SGCluster and report the results in the status.
                runAt:
                  type: string
                  description: |
                    An ISO 8601 date, that holds UTC scheduled date of the operation execution.

                    If not specified or date it’s in the past it will be interpreted as ASAP.
                timeout:
                  type: string
                  description: |
                    An ISO 8601 duration format `PnDTnHnMn.nS`, that specify a timeout after which the operation execution will not be performed.

                    If the operation can not be performed due to timeout expiration the condition `Failed` will have a status of `True` and and the reason will be `TimedOut`.

                    If not specified the operation will never fail for timeout expiration.
                maxRetries:
                  type: integer
                  description: |
                    The maximum number of retries the operation is allowed to do after a failure.

                    If not specified this default to `1`. Can not be greater than `10`.
                benchmark:
                  type: object
                  properties:
                    type:
                      type: string
                      description: |
                        The type of benchmark that will be performed on the SGCluster. Available benchamrks are:

                        * `pgbench`: run [pgnech](https://www.postgresql.org/docs/current/pgbench.html) on the specified SGCluster and report the results in the status.
                    pgbench:
                      type: object
                      properties:
                        databaseSize:
                          type: string
                          pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi|Ti)$'
                          description: |
                            Size of the database to generate. This size is specified either in Mebibytes, Gibibytes or Tebibytes (multiples of 2^20, 2^30 or 2^40, respectively).
                        duration:
                          type: string
                          description: |
                            An ISO 8601 duration format `PnDTnHnMn.nS`, that specify the duration of the benchmark.
                        type:
                          type: string
                          description: |
                            tpc.
                        usePreparedStatements:
                          type: boolean
                          description: |
                            Use extended query protocol with prepared statements. If not specified is considered `false`.
                        concurrentClients:
                          type: integer
                          description: |
                            Number of clients simulated, that is, number of concurrent database sessions. Default is 1.
                        threads:
                          type: integer
                          description: |
                            Number of worker threads within pgbench. Using more than one thread can be helpful on multi-CPU machines. Clients are distributed as evenly as possible among available threads. Default is 1.
                    connectionType:
                      type: string
                      description: |
                        Specify where the benchmark connection will be directed:

                        * `primary-service`: Connect to the primary service
                        * `replicas-service`: Connect to the replicas service
              required: ["sgCluster", "op"]
            status:
              type: object
              properties:
                conditions:
                  type: array
                  description: |
                    Possible conditions are:

                    * Running: to indicate when the operation is actually running
                    * Completed: to indicate when the operation is completed successfully
                    * Failed: to indicate when the operation had failed
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status to another.
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                        type: string
                      reason:
                        description: The reason for the condition's last transition.
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type of deployment condition.
                        type: string
                opRetries:
                  type: integer
                  description: |
                    The number of retries performed by the operation
                opStarted:
                  type: string
                  description: |
                    The ISO 8601 timestamp of when the operation started running
                benchmark:
                  type: object
                  description: |
                    The results of the benchmark
                  properties:
                    pgbench:
                      type: object
                      description: |
                        The results of the pgbench benchmark
                      properties:
                        scaleFactor:
                          type: number
                          nullable: true
                          description: |
                            The scale factor user to run pgbench (`--scale`).
                        transactionsProcessed:
                          type: integer
                          nullable: true
                          description: |
                            The number of transaction processed.
                        latencyAverage:
                          type: number
                          nullable: true
                          description: |
                            Average latency of transactions.
                        latencyStddev:
                          type: number
                          nullable: true
                          description: |
                            Stdandard deviation latency of transactions.
                        tpsIncludingConnectionsEstablishing:
                          type: number
                          nullable: true
                          description: |
                            Number of transaction per second including connection establishing.
                        tpsExcludingConnectionsEstablishing:
                          type: number
                          nullable: true
                          description: |
                            Number of transaction per second excluding connection establishing.
