cluster:
  backup:
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
    s3:
      prefix: s3://stackgres
      endpoint: http://backupconf-removal-minio.backupconf-removal.svc:9000
      forcePathStyle: true
      region: k8s
      accessKey:
        name: backupconf-removal-minio
        key: accesskey
      secretKey:
        name: backupconf-removal-minio
        key: secretkey
