config:
  backup:
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
profiles:
  - name: size-xs
    cpu: 500m
    memory: 256Mi
minio:
  persistence:
    size: 128Mi
