config:
  backup:
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
    fullWindow: 1
    volumeWriteManyStorageClass: nfs
    volumeSize: 128Mi
    minio:
      create: false
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
profiles:
  - name: size-xs
    cpu: 500m
    memory: 256Mi
