instanceProfiles: false
configurations:
  create: false
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
    instanceProfiles: 'size-xs'
  prometheusAutobind: false
minio:
  create: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
