config:
  backup:
    create: false
    minio:
      create: false
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
profiles:
  - name: size-xs
    cpu: 500m
    memory: 256Mi
