config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
  backup:
    create: false
    minio:
      create: false
  restore:
    create: false
cluster:
  volumeSize: 128Mi
  backupconfig: null
sidecar:
  prometheus:
    allowAutobind: false
nonProduction:
  disableClusterPodAntiAffinity: true
authentication:
  user: e2e
  password: test
