config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
      log_min_duration_statement: '0'
      log_checkpoints: on
      log_connections: on
      log_disconnections: on
      log_lock_waits: on
      log_replication_commands: on
  backup:
    create: false
    minio:
      create: false
  restore:
    create: false
cluster:
  volumeSize: 128Mi
  backupconfig: null
sidecar:
  prometheus:
    allowAutobind: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
