configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  postgresVersion: "12.3"
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
  prometheusAutobind: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
