configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  prometheusAutobind: false
nonProductionOptions:
  createMinio: true