config:
  backup:
    create: false
    minio:
      create: false
cluster:
  volumeSize: 128Mi
  backupconfig: null
sidecar:
  prometheus:
    allowAutobind: true
profiles:
  - name: size-xs
    cpu: 500m
    memory: 256Mi
