config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
  backup:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
    fullWindow: 1
    diskRateLimit: 16777216
    minio:
      create: false
    s3:
      prefix: s3://restore-with-minio-storage
      accessKey:
        name: restore-with-minio-storage-minio
        key: accesskey
      secretKey:
        name: restore-with-minio-storage-minio
        key: secretkey
      region: k8s
      forcePathStyle: true
      endpoint: http://restore-with-minio-storage-minio.restore-with-minio-storage.svc.cluster.local:9000
  restore:
    create: false
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
