config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
  backup:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    fullSchedule: '0 5 31 2 *'
    fullWindow: 1
    diskRateLimit: 16777216
    minio:
      create: false
    s3Compatible:
      bucket: restore-backup
      accessKey:
        name: restore-backup-minio
        key: accesskey
      secretKey:
        name: restore-backup-minio
        key: secretkey
      region: k8s
      enablePathStyleAddressing: true
      endpoint: http://restore-backup-minio.restore-backup.svc.cluster.local:9000  
cluster:
  volumeSize: 128Mi
sidecar:
  prometheus:
    allowAutobind: false
