config:
  postgresql:
    postgresql.conf:
      shared_buffers: '32MB'
  backup:
    create: false
    minio:
      create: false
  restore:
    create: false
cluster:
  volumeSize: 128Mi
  backupconfig: null
  restore:
    downloadDiskConcurrency: 1
sidecar:
  prometheus:
    allowAutobind: false
