configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid backups before waiting for pods (since backup pods could biase the wait)
    baseBackups:
      cronSchedule: '0 5 31 2 *'
      performance:
        maxDiskBandwitdh: 16777216
    storage:
      s3Compatible:
        bucket: restore-backup
        awsCredentials:
          secretKeySelectors:
            accessKeyId:
              name: restore-backup-minio
              key: accesskey
            secretAccessKey:
              name: restore-backup-minio
              key: secretkey
        region: k8s
        enablePathStyleAddressing: true
        endpoint: http://restore-backup-minio.restore-backup.svc.cluster.local:900
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  prometheusAutobind: false
minio:
  create: false
