config:
  create: true
  postgresql:
    version: "11.5"
  pgbouncer:
    version: "1.11.0"
  postgres_exporter:
    version: "0.5.1"
  envoy:
    version: "1.12.0"

cluster:
  create: true
  name: "stackgres"
  instances: 1
  pgconfig: postgresconf
  poolingconfig: pgbouncerconf
  profile: size-xs
  volumesize: 5Gi
  storageclass: standard

sidecar:
  pooling: true
  util: true
  prometheus:
    create: true
    allow_autobind: true

crd:
  version: v1alpha1

profiles:
  create: true

