config:
  create: true
  postgresql:
    version: "11.5"
  pgbouncer:
    version: "1.11.0"
  postgres_exporter:
    version: "0.5.1"
  envoy:
    version: "1.12.0"

cluster:
  create: true
  name: "stackgres"
  instances: 1
  pgconfig: postgresconf
  poolingconfig: pgbouncerconf
  profile: size-xs
  volumesize: 5Gi
  storageclass: standard
  backup:
    name: backupconf
    retention: 5
    fullSchedule: "0 5 * * *"
    fullWindow: 60
    compressionMethod: lz4
    uploadDiskConcurrency: 1
    tarSizeThreshold: 1073741823
    #networkRateLimit:
    #diskRateLimit:
    #pgpConfiguration:
    #  name: pgpConfiguration
    #  key: key
    s3: {}
    #  prefix: s3://stackgres
    #  accessKey:
    #    name: minio
    #    key: accesskey
    #  secretKey:
    #    name: minio
    #    key: secretkey
    #  region: k8s
    #  endpoint: minio.stackgres.svc
    #  forcePathStyle: true
    #  storageClass:
    #  sse:
    #  sseKmsId:
    #  cseKmsId:
    #  cseKmsRegion:
    gcs: {}
    #  prefix: gcs://stackgres
    #  serviceAccountJsonKey:
    #    name: gcs
    #    key: key
    azureblob: {}
    #  prefix: azure://stackgres
    #  account:
    #    name: azureblob
    #    key: account
    #  accessKey:
    #    name: azureblob
    #    key: accesskey
    #  bufferSize:
    #  maxBuffers:
sidecar:
  pooling: true
  util: true
  prometheus:
    create: true
    allow_autobind: true

crd:
  version: v1alpha1

profiles:
  create: true
