config:
  create: true
  postgresql:
    version: "12.2"
    postgresql.conf:
      shared_buffers: '256MB'
      random_page_cost: '1.5'
      password_encryption: 'scram-sha-256'
      wal_compression: 'on'
      checkpoint_timeout: '30'
  pgbouncer:
    pgbouncer.ini:
      pool_mode: transaction
      max_client_conn: '200'
      default_pool_size: '200'
  backup:
    create: true
    retention: 5
    fullSchedule: "*/2 * * * *"
    fullWindow: 2
    compressionMethod: lz4
    uploadDiskConcurrency: 1
    tarSizeThreshold: 1073741823
    minio:
      create: true
    #networkRateLimit:
    #diskRateLimit:
    s3: {}
    #  prefix: s3://stackgres
    #  accessKey:
    #    name: awscredentials
    #    key: accesskey
    #  secretKey:
    #    name: awscredentials
    #    key: secretkey
    s3compatible: {}
    #  prefix: s3://stackgres
    #  accessKey:
    #    name: minio
    #    key: accesskey
    #  secretKey:
    #    name: minio
    #    key: secretkey
    #  region: k8s
    #  endpoint: minio.stackgres.svc
    #  forcePathStyle: true
    #  storageClass:
    gcs: {}
    #  prefix: gcs://stackgres
    #  serviceAccountJsonKey:
    #    name: gcscredentials
    #    key: key
    azureblob: {}
    #  prefix: azure://stackgres
    #  account:
    #    name: azureblobcredentials
    #    key: account
    #  accessKey:
    #    name: azureblobcredentials
    #    key: accesskey
  

cluster:
  create: true
  instances: 1
  pgconfig: postgresconf
  poolingconfig: pgbouncerconf
  backupconfig: backupconf
  profile: size-xs
  volumeSize: 5Gi  
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  #storageClass: "-"

sidecar:
  pooling: true
  util: true
  prometheus:
    allowAutobind: true

profiles:
  - name: size-xs
    cpu: "500m"
    memory: "512Mi"
  - name: size-s
    cpu: "1"
    memory: "2Gi"
  - name: size-m
    cpu: "2"
    memory: "4Gi"
  - name: size-l
    cpu: "4"
    memory: "8Gi"
  - name: size-xl
    cpu: "6"
    memory: "16Gi"
  - name: size-xxl
    cpu: "8"
    memory: "32Gi"

minio:
  persistence:
    enabled: true
    size: 10Gi
  buckets:
    - name: stackgres
      policy: none
      purge: true

#You should only set following options for non production environment
nonProduction:
  disableClusterPodAntiAffinity: true
