{{- if and .Values.deploy.restapi .Values.authentication }}
{{- if or .Values.authentication.user .Values.authentication.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restapi.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    api.stackgres.io/auth: user
type: Opaque
data:
  k8sUsername: {{ if .Values.authentication.user }}{{ .Values.authentication.user | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  password: {{ if .Values.authentication.password }}{{ .Values.authentication.password | sha256sum | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | sha256sum | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}