apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgbackups.{{ .Values.group }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresBackup
    listKind: StackGresBackupList
    plural: sgbackups
    singular: sgbackup
  validation:
    openAPIV3Schema:
      type: object
      description: "Status of backup"
      properties:
        spec:
          type:
          properties:
            isPermanent:
              type: boolean
              description: "Indicate if this backup is permanent and should not be removed by retention process."
        status:
          type: object
          properties:
            phase:
              type: string
              enum: [ "pending", "completed", "failed" ]
              description: "The phase of the backup."
            pod:
              type: string
              description: "The name of pod assigned to this backup."
            failureReason:
              type: string
              description: "If the phase is failed this field will contain a message with the failure reason."
            backupConf:
              type: string
              description: "The name of the backup configuration used to perform this backup."
            name:
              type: string
              description: "The name of the backup."
            lastModified:
              type: string
              format: date-time
              description: "The last modified date of the backup."
            walSegmentBackupStart:
              type: string
              description: "The WAL segment when backup was started."
            startTime:
              type: string
              format: date-time
              description: "The start time of backup."
            finishTime:
              type: string
              format: date-time
              description: "The finish time of backup."
            hostname:
              type: string
              description: "The hostname of instance where the backup is taken."
            dataDir:
              type: string
              description: "The data directory where the backup is taken."
            pgVersion:
              type: string
              description: "The PostgreSQL version of the server where backup is taken."
            startLsn:
              type: string
              description: "The LSN of when backup started."
            finishLsn:
              type: string
              description: "The LSN of when backup finished."
            size:
              type: integer
              format: int64
              description: "The size in bytes of the backup."
            controlData:
              type: object
              description: "An object containing data from the output of pg_controldata on the backup."
            tested:
              type: boolean
              description: "true if the backup has been tested."
