apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
type: Opaque
{{- if or .Values.cert.key .Values.cert.crt }}
data:
  {{- if .Values.cert.key }}
  root.key: {{ .Values.cert.key }}
  {{- end }}
  {{- if .Values.cert.crt }}
  server.crt: {{ .Values.cert.crt }}
  {{- end }}
{{- end }}
