apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- if or .Values.cert.key .Values.cert.crt }}
data:
  {{- if .Values.cert.key }}
  root.key: {{ .Values.cert.key }}
  {{- end }}
  {{- if .Values.cert.crt }}
  server.crt: {{ .Values.cert.crt }}
  {{- end }}
{{- end }}