apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user: "{{ .Values.authentication.user | b64enc }}"
  password: "{{ .Values.authentication.password | b64enc }}"
{{- if or .Values.cert.key .Values.cert.crt }}
  {{- if .Values.cert.key }}
  root.key: {{ .Values.cert.key }}
  {{- end }}
  {{- if .Values.cert.crt }}
  server.crt: {{ .Values.cert.crt }}
  {{- end }}
{{- end }}