{{- if and .Values.cert.key .Values.cert.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root.key: {{ .Values.cert.key }}
  server.crt: {{ .Values.cert.crt }}
{{ end }}