apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: sgcluster.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgclusters"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgcluster'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
  - name: sgpgconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgpgconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgpgconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
  - name: sgconnectionpoolingconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgconnectionpoolingconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgconnectionpoolingconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
  - name: sgprofile.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgprofiles"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgprofile'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
  - name: sgbackupconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackupconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackupconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
  - name: sgbackup.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackups"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackup'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
