apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
webhooks:
  - name: sgcluster.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgclusters"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgcluster'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sgpgconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgpgconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgpgconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sgpoolconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgpoolconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgpoolconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sginstanceprofile.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sginstanceprofiles"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sginstanceprofile'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sgbackupconfig.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackupconfigs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackupconfig'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sgbackup.{{ .Release.Name }}.{{ .Release.Namespace }}
    {{- if gt (atoi (mustRegexReplaceAll "^([0-9]+)[^0-9]*$" .Capabilities.KubeVersion.Minor "${1}")) 12 }}
    sideEffects: None
    {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgbackups"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgbackup'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- else }}
      caBundle: ""
      {{- end }}
  - name: sgdistributedlogs.{{ .Release.Name }}.{{ .Release.Namespace }}
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: ["stackgres.io"]
        apiVersions: ["*"]
        resources: ["sgdistributedlogs"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Release.Name }}
        path: '/stackgres/validation/sgdistributedlogs'
      {{- if .Values.cert.crt }}
      caBundle: {{ .Values.cert.crt }}
      {{- end }}
