{{- if .Values.deploy.restapi }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.restapi.name  }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  {{- if .Values.service.loadBalancer.enabled }}
  type: LoadBalancer
  {{- with .Values.service.loadBalancer.loadBalancerIP }}
  loadBalancerIP: "{{ . }}"
  {{- end }}
  {{- with .Values.service.loadBalancer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range . }}
    - "{{ . }}"
    {{- end }}
  {{- end }}
  {{- else }}
  type: '{{ .Values.service.type }}'
  {{- end }}
  selector:
    app: {{ .Values.restapi.name }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
{{- end }}
