apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgclusters.{{ .Values.group }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresCluster
    listKind: StackGresClusterList
    plural: sgclusters
    singular: sgcluster
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      description: "Params for StackGres Cluster creation"
      properties:
        spec:
          type: object
          properties:
            instances:
              type: integer
            pg_version:
              type: string
            pg_config:
              type: string
            connection_pooling_config:
              type: string
            resource_profile:
              type: string
            volume_size:
              type: string
            storage_class:
              type: string
            sidecars:
              type: array
          required: [
            "instances",
            "pg_version",
            "pg_config",
            "connection_pooling_config",
            "resource_profile",
            "volume_size",
            "storage_class",
            "sidecars"
          ]




