apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgclusters.{{ .Values.group }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresCluster
    listKind: StackGresClusterList
    plural: sgclusters
    singular: sgcluster
  validation:
    openAPIV3Schema:
      type: object
      required: ["spec"]
      description: "Params for StackGres Cluster creation"
      properties:
          spec:
            type: object
            properties:
              instances:
                type: integer
                minimum: 1
                description: "Number of instances to be created"
              pg_version:
                type: string
                enum:
                - "11.5"
                - "12.0"
                description: "PostgreSQL version for the new cluster"
              pg_config:
                type: string
                description: "PostgreSQL configuration to apply"
              connection_pooling_config:
                type: string
                description: "Pooling configuration to apply"
              resource_profile:
                type: string
                description: "Resource profile size to apply"
              volume_size:
                type: string
                pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi|Ti)$'
                description: "Storage volume size"
              storage_class:
                type: string
                description: "Storage class name to be used for the cluster"
              sidecars:
                type: array
                items:
                  type: string
                description: "List of sidecars to include in the cluster"
            required: [
              "instances",
              "pg_version",
              "pg_config",
              "connection_pooling_config",
              "resource_profile",
              "volume_size",
              "storage_class",
              "sidecars"
            ]




