apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operatorName }}-nginx
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.operatorNamespace }}
  {{- end }}
data:
  stackgres-operator.conf: |
    server {
        error_log /var/log/nginx/error.log debug;
        
        server_name  localhost;
        
        listen       443 ssl;
        ssl_certificate         /etc/operator/certs/server.crt;
        ssl_certificate_key     /etc/operator/certs/root.key;
        
        {{- if and .Values.grafana.url .Values.grafana.token .Values.grafana.httpHost }}
        location /grafana {
            add_header Content-Type text/plain;
            return 200 "$scheme://$http_host{{ regexReplaceAll "^https?://[^/]+(/.*)$" .Values.grafana.url "${1}" }}";
        }
        {{ end }}
        
        location ~ ^(/|/stackgres)$ {
            return 302 "$scheme://$http_host/stackgres/";
        }
        
        location ~ ^/stackgres {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://localhost:8080;
        }
        
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            index index.html index.htm;
            {{- if and .Values.grafana.url .Values.grafana.token .Values.grafana.httpHost }}
            proxy_set_header Authorization "Bearer {{ .Values.grafana.token }}";
            proxy_hide_header X-Frame-Options;
            proxy_pass "{{ default "http" .Values.grafana.scheme }}://{{ regexReplaceAll "/" .Values.grafana.httpHost "" }}";
            {{ else }}
            return 404;
            {{ end }}
        }
    }

