apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgprofiles.{{ .Values.group }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresProfile
    listKind: StackGresProfileList
    plural: sgprofiles
    singular: sgprofile
  validation:
    openAPIV3Schema:
      required: ["spec"]
      type: object
      description: "Params for resources"
      properties:
        spec:
          type: object
          properties:
            cpu:
              type: string
              pattern: '^[1-9][0-9]*[m]?$'
              description: "CPU amount to be used"
            memory:
              type: string
              pattern: '^[0-9]+(\.[0-9]+)?(Mi|Gi)$'
              description: "Memory size to be used"
          required: ["cpu","memory"]