apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sgprofiles.{{ .Values.group }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: {{ .Values.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: StackGresProfile
    listKind: StackGresProfileList
    plural: sgprofiles
    singular: sgprofile
  preserveUnknownFields: false #Force to use structural schema
  validation:
    openAPIV3Schema:
      required: ["spec"]
      type: object
      description: "Params for resources"
      properties:
        spec:
          type: object
          properties:
            cpu:
              type: string
            memory:
              type: string            
            volumeSize:
              type: string
          required: ["cpu","memory","volumeSize"]