{{- if .Values.cert.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.operatorName }}
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.operatorNamespace }}
  {{- end }}
type: Opaque
data:
  root.key: {{ .Values.cert.key }}
  server.crt: {{ .Values.cert.crt }}
{{ end }}