{{ if .Values.cluster.create }}
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresCluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  pg_version: '{{ .Values.config.postgresql.version }}'
  pg_config: '{{ .Values.cluster.pgconfig }}'
  connection_pooling_config: '{{ .Values.cluster.poolingconfig }}'
  resource_profile: '{{ .Values.cluster.profile }}'
  volume_size: '{{ .Values.cluster.volumesize }}'
  storage_class: '{{ .Values.cluster.storageclass }}'
  sidecars:
  {{- if .Values.sidecar.pooling }}
  - connection-pooling
  {{ end }}
  {{- if .Values.sidecar.util }}
  - postgres-util
  {{- end }}
  {{- if .Values.sidecar.prometheus }}
  - prometheus-postgres-exporter
  {{- end }}
{{ end }}
