{{ if .Values.profiles.create }}
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xs
spec:
  cpu: "500m"
  memory: "512Mi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-s
spec:
  cpu: "1"
  memory: "2Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-m
spec:
  cpu: "2"
  memory: "4Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-l
spec:
  cpu: "4"
  memory: "8Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xl
spec:
  cpu: "6"
  memory: "16Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xxl
spec:
  cpu: "8"
  memory: "32Gi"
{{ end }}