{{ if .Values.profiles.create }}
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xs
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "500m"
  memory: "512Mi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-s
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "1"
  memory: "2Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-m
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "2"
  memory: "4Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-l
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "4"
  memory: "8Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xl
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "6"
  memory: "16Gi"
---
apiVersion: stackgres.io/{{ .Values.crd.version }}
kind: StackGresProfile
metadata:
  name: size-xxl
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  cpu: "8"
  memory: "32Gi"
{{ end }}
